/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: lizhou ding (https://sketchfab.com/vancchino)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/anime-style-80s-computer-f6d5720e0ab742f7b2359fff156fbfae
Title: Anime Style 80's Computer
*/

import React, { useRef,useEffect } from 'react'
import { useGLTF, useVideoTexture } from '@react-three/drei'
import gsap from 'gsap'



const DemoComputer = (props)=> {
  const group = useRef(null);
  const { nodes, materials } = useGLTF('/models/anime_style_80s_computer.glb')
  //console.log("anime computer:",nodes);
 
  // const texture = useVideoTexture(props.texture)
  // useEffect(() => {
  //   if (group.current) {
  //     gsap.from(group.current.rotation, {
  //       y: Math.PI / 2,
  //       duration: 1,
  //       ease: 'power3.out',
  //     });
  //   }
  // }, [texture]);

  // useEffect(()=>{
  //   if(texture)
  //     texture.flipY = true;
 
  // },[texture])


  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0.13} >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube8_phong1_0.geometry}
          material={materials.phong1}
        >
       
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube8_standardSurface1_0.geometry}
          material={materials.standardSurface1}
        >

          </mesh>
      
        {/* <mesh position={[0.15, 6, 2.8]} scale={5} rotation={[0, 0, 0]}>
  <planeGeometry args={[1.18, 0.97]} />
  <meshBasicMaterial map={props.texture} />
</mesh> */}
      </group>
    </group>
  )
}

useGLTF.preload('/models/anime_style_80s_computer.glb')
export default DemoComputer
